version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - gallery
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: root_pass
      MONGO_INITDB_DATABASE: gallery

networks:
  gallery:
